# Site Configuration
title: "Jekyll Site - Learning Project"
subtitle: "Getting up-to-speed with jekyll"
email: your-email@example.com
description: "Practicing how to set-up and maintain a blog website using the Jekyll - a static site generator."

# Path information
baseurl: ""
url: ""

# Social media accounts
twitter_username: roblaws75
github_username:  robert-laws

# Build settings
markdown: kramdown
future: true
highlighter: rouge
# permalink: /posts/:title
kramdown:
  auto_ids: false
  input: GFM
  syntax_highlighter: rouge


# Plugins
plugins: [jekyll-paginate]

# Pagination
paginate: 2
paginate_path: '/post/page:num/'
permalink: /post/:title